/**
 * Research Service
 * Provides factual research retrieval with provenance (mock knowledge base)
 */

import { encodeText, cosine } from '../vsa/encoder.mjs';

// Mock knowledge base for research phase
const KNOWLEDGE_BASE = [
  {
    id: 'kb_001',
    title: 'Storm Surge Definition',
    content: 'A storm surge is an abnormal rise of water generated by a storm, over and above the predicted astronomical tides.',
    source: 'NOAA Weather Service',
    domain: 'meteorology',
    tags: ['weather', 'storm', 'ocean']
  },
  {
    id: 'kb_002',
    title: 'CRISPR Technology Overview',
    content: 'CRISPR-Cas9 is a genome editing tool that allows scientists to alter DNA sequences and modify gene function.',
    source: 'NIH National Human Genome Research Institute',
    domain: 'biology',
    tags: ['genetics', 'biotechnology', 'science']
  },
  {
    id: 'kb_003',
    title: 'Three-Act Structure',
    content: 'The three-act structure divides a story into Setup, Confrontation, and Resolution. Each act serves a distinct narrative purpose.',
    source: 'Aristotle, Poetics',
    domain: 'writing',
    tags: ['narrative', 'structure', 'storytelling']
  },
  {
    id: 'kb_004',
    title: "Hero's Journey",
    content: "Joseph Campbell's monomyth describes 17 stages of the hero's journey: departure, initiation, and return, with archetypes common across cultures.",
    source: 'Campbell, J. (1949). The Hero with a Thousand Faces',
    domain: 'mythology',
    tags: ['narrative', 'archetype', 'mythology']
  },
  {
    id: 'kb_005',
    title: 'Character Consistency in Fiction',
    content: 'Character consistency requires maintaining established traits, motivations, and speech patterns throughout a narrative to preserve reader trust.',
    source: 'McKee, R. Story: Substance, Structure, Style',
    domain: 'writing',
    tags: ['character', 'consistency', 'fiction']
  },
  {
    id: 'kb_006',
    title: 'Copyright and AI-Generated Content',
    content: 'AI-generated works raise complex copyright questions. The US Copyright Office requires human authorship for registration.',
    source: 'US Copyright Office AI Policy (2023)',
    domain: 'law',
    tags: ['copyright', 'ai', 'legal']
  },
  {
    id: 'kb_007',
    title: 'Narrative Coherence',
    content: 'Narrative coherence refers to the logical and causal connections between events in a story. It includes temporal, causal, and referential coherence.',
    source: 'Jurafsky & Martin, Speech and Language Processing',
    domain: 'linguistics',
    tags: ['coherence', 'narrative', 'nlp']
  },
  {
    id: 'kb_008',
    title: 'Vector Symbolic Architectures',
    content: 'VSA/HDC uses high-dimensional vectors for symbolic computation. Key operations: bundling (superposition), binding (association), and permutation.',
    source: 'Kanerva, P. Hyperdimensional Computing (2009)',
    domain: 'computer science',
    tags: ['vsa', 'hdc', 'computing']
  },
  {
    id: 'kb_009',
    title: 'Bias in AI Systems',
    content: 'AI bias can manifest as stereotyping, underrepresentation, or unfair treatment. Mitigation requires diverse training data and evaluation.',
    source: 'UNESCO AI Ethics Recommendation (2021)',
    domain: 'ethics',
    tags: ['bias', 'ai', 'ethics']
  },
  {
    id: 'kb_010',
    title: 'Emotional Arc Patterns',
    content: 'Kurt Vonnegut identified emotional arc patterns: Man in Hole (fall-rise), Icarus (rise-fall), Cinderella (rise-fall-rise), and others.',
    source: 'Vonnegut, K. Shape of Stories',
    domain: 'writing',
    tags: ['emotion', 'arc', 'narrative']
  }
];

/**
 * Search knowledge base using VSA similarity
 */
function searchKnowledgeBase(query, options = {}) {
  const topK = options.top_k || 5;
  const minScore = options.min_score || 0.3;
  const domains = options.domains || [];
  const dim = options.dim || 1000;
  const seed = options.seed || 42;
  
  // Encode query
  const queryVector = encodeText(query, dim, seed);
  
  // Score each knowledge base entry
  const scored = KNOWLEDGE_BASE.map(entry => {
    // Filter by domain if specified
    if (domains.length > 0 && !domains.includes(entry.domain)) {
      return { entry, score: 0 };
    }
    
    // Combine title and content for matching
    const entryText = `${entry.title} ${entry.content} ${entry.tags.join(' ')}`;
    const entryVector = encodeText(entryText, dim, seed);
    const score = cosine(queryVector, entryVector);
    
    return { entry, score };
  });
  
  // Sort and filter
  const results = scored
    .filter(s => s.score >= minScore)
    .sort((a, b) => b.score - a.score)
    .slice(0, topK)
    .map(s => ({
      id: s.entry.id,
      title: s.entry.title,
      snippet: s.entry.content.slice(0, 200),
      source: s.entry.source,
      domain: s.entry.domain,
      relevance_score: s.score,
      provenance: {
        source_id: s.entry.id,
        source_name: s.entry.source,
        retrieved_at: new Date().toISOString()
      }
    }));
  
  return {
    query,
    results,
    total_found: results.length,
    search_params: { top_k: topK, min_score: minScore, domains }
  };
}

/**
 * Get a specific knowledge base entry by ID
 */
function getKnowledgeEntry(id) {
  return KNOWLEDGE_BASE.find(e => e.id === id) || null;
}

export {
  searchKnowledgeBase,
  getKnowledgeEntry,
  KNOWLEDGE_BASE
};
